name: Build (multi-OS)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Setup build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 make g++ clang-format

      - name: Setup build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install python@3 || true
          brew install llvm || true

      - name: Setup build tools (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          npm install --global windows-build-tools@5.2.2 || true
          npm config set msvs_version 2019
          choco install -y python --version=3.11.9 || choco upgrade -y python || $true

      - name: Install dependencies
        run: npm ci

      - name: Build (node-gyp + tsc)
        run: npm run build

      - name: Show built artifact
        run: |
          node -e "console.log('exists:', require('fs').existsSync('build/Release/seshat.node'))"


